package com.luthertools.fretcalculator.model

data class FretRequest(
    val scaleLength: Double,
    val numberOfFrets: Int,
    val nutWidth: Double,
    val width12thFret: Double,
    val unit: Unit = Unit.MM,
    val showFretNumbers: Boolean = true,
    val showCenterLine: Boolean = true,
    val showWidthAnnotations: Boolean = true,
    val showInlays: Boolean = true,
    val doubleInlays: Boolean = true,
    val inlayShape: InlayShape = InlayShape.CIRCLE,
    val inlaySize: Double = 6.0,
    val inlayHeight: Double = 4.0,
    val inlayPosition: InlayPosition = InlayPosition.CENTER,
    val inlayDoubleOffset: Double = 8.0,
    val inlayShrinkWidth1224: Double = 0.0,
    val inlayShrinkHeight1224: Double = 0.0,
    val inlayShrinkWidth: Double = 0.0,
    val inlayGrowHeight: Double = 0.0,
    val inlayTrapezoid: Double = 0.0,
    val inlayParallelogram: Double = 0.0,
    val showBoundingBox: Boolean = false,
    val label: String = "",
    val showRadius: Boolean = false,
    val radiusValue: Double = 305.0,
    val radiusSteps: Int = 5,
    val showNutSlot: Boolean = false,
    val nutSlotWidth: Double = 5.5,
    val nutSlotDistance: Double = 0.0,
    val showPinholes: Boolean = false,
    val tangWidth: Double = 0.6,
    val fretExtensionAmount: Double = 0.0,
    val inlayDoubleOrientation: InlayDoubleOrientation = InlayDoubleOrientation.VERTICAL,
    // Polygon points for InlayShape.CUSTOM, normalized to [0,1]² (x: left→right, y: top→bottom).
    // Each entry is a 2-element list [x, y]. Empty list disables custom rendering.
    val inlayCustomPath: List<List<Double>> = emptyList(),
)
